Add 'tazwok cmp --cook'

diff --git a/tazwok b/tazwok
--- a/tazwok
+++ b/tazwok
@@ -613,7 +613,7 @@ hgdate()
 	local date
 	local mon
 	# Default date is Jan 1 1970
-	[ -d $WOK/.hg ] || return 0
+	[ -d $WOK/.hg -a -x /usr/bin/hg ] || { echo "0"; return; }
 	pkg=$(basename $1)
 	# Get date for last commit
 	date="$( cd $WOK; hg log $(find $pkg/receipt $pkg/stuff -type f \
@@ -710,34 +710,39 @@ Cooked packages      : `ls -1 $PACKAGES_REPOSITORY/*.tazpkg 2>/dev/null | wc -l`
 		for pkg in $WOK/*
 		do
 			. $pkg/receipt
-			echo "$PACKAGE-$VERSION.tazpkg" >> /tmp/wok.list
+			echo "$PACKAGE-$VERSION.tazpkg" >> /tmp/wok.list.$$
 			tpkg="$(ls $PACKAGES_REPOSITORY/$PACKAGE-$VERSION*.tazpkg 2> /dev/null)"
 			if [ -z "$tpkg" ]; then
 				echo "Missing package: $PACKAGE ($VERSION)"
-				echo "$PACKAGE" >> /tmp/pkgs.missing
+				echo "$PACKAGE" >> /tmp/pkgs.missing.$$
 			elif [ -f $pkg/taz/*/receipt -a ! -f $pkg/taz/*/md5sum ]; then
 				echo "Obsolete package: $PACKAGE ($VERSION)"
-				echo "$PACKAGE" >> /tmp/pkgs.missing
+				echo "$PACKAGE" >> /tmp/pkgs.missing.$$
 			else
 				srcdate=$(hgdate $pkg)
 				pkgdate=$(date -u -r $tpkg '+%m%d%H%M%Y')
 				if [ $(date -d $pkgdate +%s) -lt $(date -d $srcdate +%s) ]; then
 					echo "Rebuild package: $PACKAGE ($VERSION) cooked $(date -d $pkgdate "+%x %X"), modified $(date -d $srcdate "+%x %X")"
-					echo "$PACKAGE" >> /tmp/pkgs.missing
+					echo "$PACKAGE" >> /tmp/pkgs.missing.$$
+				else
+					continue
 				fi
+			fi
+			if [ "$2" = "--cook" ]; then
+				tazwok cook $PACKAGE
 			fi
 		done
 		for pkg in `cd $PACKAGES_REPOSITORY && ls *.tazpkg`
 		do
-			# grep $pkg in /tmp/wok.list
+			# grep $pkg in /tmp/wok.list.$$
 			# may include EXTRAVERSION or computed VERSION
-			for i in $(grep ^${pkg%-*} /tmp/wok.list); do
+			for i in $(grep ^${pkg%-*} /tmp/wok.list.$$); do
 				case "$pkg" in
 				${i%.tazpkg}*.tazpkg) continue 2;;
 				esac
 			done
 			# Not found
-			echo $pkg >> /tmp/pkgs.old
+			echo $pkg >> /tmp/pkgs.old.$$
 			if [ "$2" = "--remove" ]; then
 				echo "Removing package: $pkg"
 				rm $PACKAGES_REPOSITORY/$pkg
@@ -747,12 +752,12 @@ Cooked packages      : `ls -1 $PACKAGES_REPOSITORY/*.tazpkg 2>/dev/null | wc -l`
 		done
 		cd /tmp
 		echo "================================================================================"
-		echo "Wok: `cat wok.list | wc -l` - \
+		echo "Wok: `cat wok.list.$$ | wc -l` - \
 Cooked: `ls -1 $PACKAGES_REPOSITORY/*.tazpkg 2>/dev/null | wc -l` - \
-Missing: `cat pkgs.missing 2>/dev/null | wc -l` - \
-Old: `cat pkgs.old 2>/dev/null | wc -l`"
+Missing: `cat pkgs.missing.$$ 2>/dev/null | wc -l` - \
+Old: `cat pkgs.old.$$ 2>/dev/null | wc -l`"
 		echo ""
-		rm -f wok.list pkgs.old pkgs.missing
+		rm -f wok.list.$$ pkgs.old.$$ pkgs.missing.$$
 		;;
 	list)
 		# List packages in wok directory. User can specifiy a category
@@ -908,16 +913,22 @@ Maintainer : $MAINTAINER"
 		# Remove taz/ and source tree if exists.
 		if [ -d "taz" ]; then
 			echo -n "Removing taz files..."
-			rm -rf taz && status
+			rm -rf taz
+			status
 		fi
-		if [ -d "$PACKAGE-$VERSION" ]; then
+		for i in $PACKAGE-$VERSION $SOURCE-$VERSION ; do
+			[ -e "$i" ] || continue
 			echo -n "Removing source files..."
-			rm -rf $PACKAGE-$VERSION && status
-		fi
-		if [ -d "$SOURCE-$VERSION" ]; then
-			echo -n "Removing source files..."
-			rm -rf $SOURCE-$VERSION && status
-		fi
+			if [ -L $i ]; then
+				target=$(readlink $i)
+				[ -d "$target" ] && case "$target" in
+				/*|.|./*|..|../*);;
+				*) rm -rf $target;;
+				esac
+			fi
+			rm -rf $i
+			status
+		done
 		# Remove an envental $PACKAGE-build directory.
 		if [ -d "$PACKAGE-build" ]; then
 			echo -n "Removing build tree..."
