Fix an issue into check_for_tarball() which prevent to cook packages without  WGET_URL

diff --git a/tazwok b/tazwok
--- a/tazwok
+++ b/tazwok
@@ -435,40 +435,39 @@ remove_previous_package()
 # Check for src tarball and wget if needed.
 check_for_tarball()
 {
-	if [ "$WGET_URL" ]; then
-		report step "Checking for source tarball"
-			
-		if [ ! -f "$SOURCES_REPOSITORY/$TARBALL" ] && \
-			[ ! -f "$SOURCES_REPOSITORY/${SOURCE:-$PACKAGE}-$VERSION.tar.lzma" ] ; then
-			cd $SOURCES_REPOSITORY
-			download $WGET_URL
-			
-			# If source tarball is unreachable, try to find it on SliTaz
-			# mirror.
-			if [ ! -f "$SOURCES_REPOSITORY/$TARBALL" ]; then
-				report step "Download failed, try with mirror copy... "
-				if [ "$SOURCE" ]; then
-					download http://mirror.slitaz.org/sources/packages/${SOURCE:0:1}/$SOURCE-$VERSION.tar.lzma
-				else
-					download http://mirror.slitaz.org/sources/packages/${PACKAGE:0:1}/$PACKAGE-$VERSION.tar.lzma
-				fi
-			fi
-			if [ ! -f "$SOURCES_REPOSITORY/$TARBALL" ] && \
-				[ ! -f "$SOURCES_REPOSITORY/${SOURCE:-PACKAGE}-$VERSION.tar.lzma" ]; then
-				report step "Download failed, try with mirror copy (again)... "
-				file=$(basename $WGET_URL)
-				download http://mirror.slitaz.org/sources/packages/${file:0:1}/$file
-			fi
-
-			# Exit if download failed to avoid errors.
-			if [ ! -f "$SOURCES_REPOSITORY/$TARBALL" ] && [ ! -f "$SOURCES_REPOSITORY/${SOURCE:-PACKAGE}-$VERSION.tar.lzma" ; then
-				echo -e "\nDownload failed, exiting. Please check WGET_URL variable.\n" >&2
-				report end-step
-				return 1
+	[ "$WGET_URL" ] || return
+	report step "Checking for source tarball"
+	
+	if [ ! -f "$SOURCES_REPOSITORY/$TARBALL" ] && \
+		[ ! -f "$SOURCES_REPOSITORY/${SOURCE:-$PACKAGE}-$VERSION.tar.lzma" ] ; then
+		cd $SOURCES_REPOSITORY
+		download $WGET_URL
+		
+		# If source tarball is unreachable, try to find it on SliTaz
+		# mirror.
+		if [ ! -f "$SOURCES_REPOSITORY/$TARBALL" ]; then
+			report step "Download failed, try with mirror copy... "
+			if [ "$SOURCE" ]; then
+				download http://mirror.slitaz.org/sources/packages/${SOURCE:0:1}/$SOURCE-$VERSION.tar.lzma
+			else
+				download http://mirror.slitaz.org/sources/packages/${PACKAGE:0:1}/$PACKAGE-$VERSION.tar.lzma
 			fi
 		fi
-		report end-step
+		if [ ! -f "$SOURCES_REPOSITORY/$TARBALL" ] && \
+			[ ! -f "$SOURCES_REPOSITORY/${SOURCE:-PACKAGE}-$VERSION.tar.lzma" ]; then
+			report step "Download failed, try with mirror copy (again)... "
+			file=$(basename $WGET_URL)
+			download http://mirror.slitaz.org/sources/packages/${file:0:1}/$file
+		fi
+
+		# Exit if download failed to avoid errors.
+		if [ ! -f "$SOURCES_REPOSITORY/$TARBALL" ] && [ ! -f "$SOURCES_REPOSITORY/${SOURCE:-PACKAGE}-$VERSION.tar.lzma" ; then
+			echo -e "\nDownload failed, exiting. Please check WGET_URL variable.\n" >&2
+			report end-step
+			return 1
+		fi
 	fi
+	report end-step
 	
 	if [ -f "$SOURCES_REPOSITORY/${SOURCE:-$PACKAGE}-$VERSION.tar.lzma" ] && [ "$nounpack" ]; then
 		return
