Confirm that TARBALL exist before check if src folder doesn't exist.

diff --git a/tazwok b/tazwok
--- a/tazwok
+++ b/tazwok
@@ -531,21 +531,22 @@ check_for_tarball()
 		[ -d "$tmp_src" ] && rm -r $tmp_src
 		return
 	fi
-		
-	if [ ! -d "$src" ]; then
-		if [ -d "$tmp_src" ]; then
-			if ! check_for_var_modification src _pkg; then
-				src="${src%/*}/$(ls $tmp_src)"
-			fi
-			mv $(echo $tmp_src/*) "$src"
-			rm -r $tmp_src
+	if [ "$TARBALL" ]; then
+		if [ ! -d "$src" ]; then
+			if [ -d "$tmp_src" ]; then
+				if ! check_for_var_modification src _pkg; then
+					src="${src%/*}/$(ls $tmp_src)"
+				fi
+				mv $(echo $tmp_src/*) "$src"
+				rm -r $tmp_src
 						
-			# Permissions settings.
-			chown -R root.root "$src"
+				# Permissions settings.
+				chown -R root.root "$src"
+			fi
+			report end-step
+		else
+			echo "There's already something at $src. Abort." >&2
 		fi
-		report end-step
-	else
-		echo "There's already something at $src. Abord." >&2
 	fi
 }
 
